Feat/footer
Unimind-Dao/unimind-frontend pull request #5
Opened 2022-06-30 18:17 UTC by 99mac99

2022-06-30 18:24 UTC, TomaszKotowski requested changes

2022-06-30 18:24 UTC, TomaszKotowski commented on components/Footer/PartnersBox.tsx
> +				</Link>
Use `CustomLink`

2022-06-30 18:24 UTC, TomaszKotowski commented on components/Footer/PartnersBox.tsx
> +				</Link>
Use `CustomLink`

2022-06-30 18:24 UTC, TomaszKotowski commented on components/Footer/PartnersBox.tsx
> +				</Link>
Use `CustomLink`

2022-06-30 18:24 UTC, TomaszKotowski commented on components/Footer/PartnersBox.tsx
> +				color: 'white',
Export `sx` to variable if we did the same in another file for consistency.

2022-06-30 21:01 UTC, adiusz requested changes

2022-06-30 21:01 UTC, adiusz commented on components/CustomLink/CustomLink.tsx
> +	<Link underline='none' color='black' rel='noopener noreferrer' {...props}>
aren't double apostrophes better for JSX/HTML? Also, are you using 8 spaces? xD

2022-06-30 21:01 UTC, adiusz commented on components/Footer/EndBox.tsx
> +		flexDirection: 'row',
as agreed — we should use styled-components

2022-06-30 21:01 UTC, adiusz commented on components/Footer/PartnersBox.tsx
> +			<Box sx={{ margin: '20px' }}>
you can put this data in the array here and use map method to render these items

2022-07-30 14:02 UTC, adiusz requested changes
what about my comments from a month ago?

2022-07-31 18:28 UTC, 99mac99 commented
Take a look at the commits xD

2022-07-31 20:39 UTC, merged